baseURL = "https://richwhitjr.github.io/"
languageCode = 'en-us'
title = 'Flow'
theme = "HugoTeX"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[pagination]
  pagerSize = 3

[author]
  name = "Rich Whitcomb"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "paraiso-dark" # syntax highlighting style

[Params]
  darkmode = true
